=== tstaetter/event-bin-microservice/spec/fixtures/default.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "user": {
      "type": "object",
      "properties": {
        "stranger_id": {
          "type": "string"
        },
        "external_id": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      },
      "required": [
        "stranger_id",
        "external_id",
        "email"
      ]
    },
    "client": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "browser": {
          "type": "object",
          "properties": {
            "user_agent": {
              "type": "string"
            },
            "navigator": {
              "type": "object",
              "properties": {
                "app_code_name": {
                  "type": "string"
                },
                "app_name": {
                  "type": "string"
                },
                "app_version": {
                  "type": "string"
                },
                "cookie_enabled": {
                  "type": "boolean"
                },
                "language": {
                  "type": "string"
                },
                "platform": {
                  "type": "string"
                },
                "product": {
                  "type": "string"
                },
                "product_sub": {
                  "type": "string"
                },
                "vendor": {
                  "type": "string"
                },
                "vendor_sub": {
                  "type": "string"
                }
              },
              "required": [
                "app_code_name",
                "app_name",
                "app_version",
                "cookie_enabled",
                "language",
                "platform",
                "product",
                "product_sub",
                "vendor",
                "vendor_sub"
              ]
            }
          },
          "required": [
            "user_agent",
            "navigator"
          ]
        },
        "native": {
          "type": "object",
          "properties": {
            "os": {
              "type": "string"
            },
            "os_version": {
              "type": "string"
            },
            "platform": {
              "type": "string"
            }
          },
          "required": [
            "os",
            "os_version",
            "platform"
          ]
        },
        "server": {
          "type": "object",
          "properties": {
            "os": {
              "type": "string"
            },
            "os_version": {
              "type": "string"
            },
            "framework": {
              "type": "string"
            }
          },
          "required": [
            "os",
            "os_version",
            "framework"
          ]
        }
      },
      "required": [
        "id",
        "browser",
        "native",
        "server"
      ]
    },
    "sent_at": {
      "type": "object",
      "properties": {
        "seconds": {
          "type": "integer"
        },
        "nanos": {
          "type": "integer"
        }
      },
      "required": [
        "seconds",
        "nanos"
      ]
    },
    "properties": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "value"
          ]
        }
      ]
    }
  },
  "required": [
    "name",
    "user",
    "client",
    "sent_at",
    "properties"
  ]
}

=== tstaetter/event-bin-microservice/spec/fixtures/event.json
{
  "name": "Hello",
  "user": {
    "stranger_id": "268ceedf-713a-49c7-be26-5b06ff4d6a93",
    "external_id": "8f7f20ee-4352-4d7f-9877-35dd9615ac17",
    "email": "Hello"
  },
  "client": {
    "id": "af17a4ec-66c0-4478-89c9-c7d3646d6fc4",
    "browser": {
      "user_agent": "Hello",
      "navigator": {
        "app_code_name": "Hello",
        "app_name": "Hello",
        "app_version": "Hello",
        "cookie_enabled": true,
        "language": "Hello",
        "platform": "Hello",
        "product": "Hello",
        "product_sub": "Hello",
        "vendor": "Hello",
        "vendor_sub": "Hello"
      }
    },
    "native": {
      "os": "Hello",
      "os_version": "Hello",
      "platform": "Hello"
    },
    "server": {
      "os": "Hello",
      "os_version": "Hello",
      "framework": "Hello"
    }
  },
  "sent_at": {
    "seconds": 1637473359,
    "nanos": 10
  },
  "properties": [
    {
      "name": "Hello",
      "value": "Hello"
    }
  ]
}
